create table customers (
    id bigint generated by default as identity primary key,
    email varchar(255) not null,
    name varchar(255),
    age integer not null,
    account_balance decimal(19, 2) not null,
    existing_loan_type varchar(255),
    existing_loan_open boolean not null,
    selected_offer varchar(255)
);

create unique index uk_customers_email on customers (email);
