create table banking_records (
    id bigint generated by default as identity primary key,
    customer_id varchar(255) not null,
    transaction_id varchar(255) not null,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    email varchar(255) not null,
    transaction_date date not null,
    transaction_type varchar(255) not null,
    transaction_amount decimal(19, 2) not null,
    account_balance decimal(19, 2) not null,
    customer_age integer not null,
    customer_gender varchar(255) not null,
    account_type varchar(255) not null,
    branch_id varchar(255) not null,
    account_opening_date date not null,
    transaction_description varchar(1000),
    loan_type varchar(255),
    loan_status varchar(255)
);

create unique index uk_banking_record_row_signature
    on banking_records (transaction_id);
